### ISSUE TITLE
gmvault doesn't download chats when Gmail interface language in Japanese

### ISSUE THREAD

**Issue by nattofriends** [gaubert/gmvault#140]
gmvault says it cannot find 'Chats' folder on server. It works when I change my interface lannguage to English US, but after I change it back gmvault still does not work.

**Comment by nattofriends** [comment]
Why was this closed?

**Comment by gaubert** [comment]
It was open for two years so I thought you would never answer.
Please send me what you have instead of Chats with the japanese characters.
I will add it in the configuration and it should work.
Instead of Chats what is written with the Japanese interface ?

Thank you

**Comment by nattofriends** [comment]
It is written "チャット" without quotations.

**Comment by gaubert** [comment]
Thank I will add it and hopefully it will work in the next version.
In the mean time you could add it in the conf file gmvault.conf which in
~/.gmvault.
Just add in [Localisation]


#example with Japanesechat_folder=[ u'[Gmail]/チャット', u'[Google Mail]/チャット' ]
Just replace the russian with the Japanese.
Let me know if it worked.

Thanks
