### ISSUE TITLE
Error with 2-legged-auth

### ISSUE THREAD

**Issue by argon0011** [gaubert/gmvault#143]
Correct me if I'm wrong, but I should be able to backup any email account in my domain if I provide the enabled Domain OAuth Key/Secret?

Getting this error message after entering Consumer Key and Consumer Secret when trying to backup a user's account: 
```
gmvault-shell>gmvault sync user@domain.com -2 -c no

Use gmvault-db located in C:\Users\user/gmvault-db.

Disable deletion of emails that are in Gmvault db and not anymore in Gmail.
Authentication performed with Gmail XOAuth token.

Initiate interactive session to get XOAuth normal or 2-legged token from Gmail.

Enter your domain's OAuth consumer key: domain.com
Enter your domain's OAuth consumer secret: consumerkey
Successfully read oauth credentials.

Connect to Gmail server.

ERROR: Invalid credentials, cannot login to the gmail server. Please check your login and password or xoauth token.
```
Google Apps Manager(GAM) have stopped using Consumer Key/Secret. Checkout how they've done it: https://code.google.com/p/google-apps-manager/source/browse/trunk

**Comment by gaubert** [comment]
OAUTH deprecated so close the issue
