### ISSUE TITLE
Received an IMAP abort error

### ISSUE THREAD

**Issue by wamatt** [gaubert/gmvault#154]
I started downloading Imap messages fine. Then about 700 messages in it just freezes.

After stopping the process, I removed the .info db and quarantine  directories. And tried again. But I keep getting this error

```bash
Received an IMAP abort error. Wait 2 seconds and retrying.
Disconnecting from Gmail Server and sleeping ...
Reconnecting to the from Gmail Server.
Get XOAuth credential from /root/.gmvault/xxxx@gmail.com
```

I've also deleted /root/.gmvault config and re-authed with Google, without luck. Any ideas?

**Comment by gaubert** [comment]
This has been solved and will be released in the next version due in 10 days.

**Comment by waldoj** [comment]
:+1: Thank you, @gaubert!

**Comment by paulderdash** [comment]
Good news indeed.

**Comment by xjordanx** [comment]
I am having this error however I am RESTORING gmails from one account to another, different account. Most of them (about 8 gigs worth) restored okay, but now I get this repeated error every time at the same message. 

I am using the latest gmvault and already it has the default setting to disable imap compression, so that unexplained fix above for the sync problem will not work for me.

Any ideas?

**Comment by mrbarletta** [comment]
I am having the same issue here on ubuntu 14.04.

Is there any info we could provide? its around half way of the restore

**Comment by davidpenn** [comment]
Having the same problem above as @xjordanx above.

Gmvault v1.9

Before to Append email contents
IMAP (abort) error message = command: APPEND => socket error: EOF. traceback:Traceback (most recent call last):
  File "gmv/imap_utils.pyc", line 117, in wrapper
  File "gmv/imap_utils.pyc", line 763, in push_data
  File "gmv/mod_imap.pyc", line 328, in append
  File "imapclient/imapclient.pyc", line 949, in _command_and_check
  File "imaplib.pyc", line 324, in append
  File "imaplib.pyc", line 1070, in _simple_command
  File "imaplib.pyc", line 899, in _command_complete
abort: command: APPEND => socket error: EOF

Received an IMAP abort error. Wait 1 second(s) and retrying.
Disconnecting from Gmail Server and sleeping ...
Reconnecting to the from Gmail Server.

~/.gmvault/gmvault_defaults.conf

[General]
limit_per_chat_dir=2000
errors_if_chat_not_visible=False
nb_messages_per_batch=500
nb_messages_per_restore_batch=80
restore_default_location=DRAFTS
keep_in_bin=False
enable_imap_compression=False

**Comment by moshebomb** [comment]
I have this problem also, imap error.
My problem is how to enable_imap_compression=False , 

I am using linux  ubuntu lxde.. please help me thanks for

**Comment by paulderdash** [comment]
So is the current version 1.9 not working for restore? Is there a
work-around? i.e. set enable_imap_compression=True?

**Comment by mrbarletta** [comment]
@paulderdash  @moshebomb 
I solved this issue moving the conflicting file, let the process run , check for the last ID (e.g.1498552751286555116)   and then do a :
<pre>find . -name 1498552751286555116*</pre>
and move the files away from the folder.

**Comment by moshebomb** [comment]
@mrbarletta  yes I already did that, thank you for your post I realized what to do Kudos.. 
I already know how set  enable_imap_compression=false..

**Comment by leoshibata** [comment]
Getting the same issue on version 1.9.2 compiled on macOS Sierra 10.12.3
Checked the config file and enable_imap_compression is already set to false.

**Comment by bns14288** [comment]
I have a Business gmail account.
It synced 10000 emails approx but suddenly when i restarted from the gmvault shell.

It is throwing an error : 
Received an IMAP abort error. Wait 1 second(s) and retrying.

Received an IMAP abort error. Wait 1 second(s) and retrying.
Disconnecting from Gmail Server and sleeping ...
Reconnecting to the from Gmail Server.
Get OAuth2 credential from C:\Users\Evosys/.gmvault/bhaveshs@evosysglobal.com.oauth2.

i have also reviewed the conf file and enable_imap_compression = false.
 but it still fails i m not able to take my backup please help me on the same. Its a bit urgent.
