### ISSUE TITLE
Error: UID command error: BAD ['Could not parse command'].

### ISSUE THREAD

**Issue by fugedi** [gaubert/gmvault#156]
Hi,

This is a great tool, I have exported and restored over 200000 mails now, and I got stuck here. If you need more debug info, please tell me.

Thanks for helping.

gmvault-shell>gmvault sync --type custom -c yes --imap-req "Since 31-Dec-2009 Before 1-Jan-2011" -d d:\tar\data\gmvault\ "xxxx@xxxx.xx"

Use gmvault-db located in d:\tar\data\gmvault\.

Activate Gmvault db cleaning.
Authentication performed with Gmail XOAuth token.

Get XOAuth credential from C:\Documents and Settings\xxxx/.gmvault/xxxx@xxxx.xx.oauth.

Successfully read oauth credentials.

Connect to Gmail server.

Perform custom synchronisation with imap request: Since 31-Dec-2009 Before 1-Jan-2011.

Start synchronization (2014-01-24T15h07m06s).

Start emails synchronization.
Error when reaching Gmail server. Wait 1 seconds and retry up to 2 times.
Disconnecting from Gmail Server and sleeping ...
Reconnecting to the from Gmail Server.
Get XOAuth credential from C:\Documents and Settings\xxxx/.gmvault/xxxx@xxxx.xx.oauth.

Error when reaching Gmail server. Wait 2 seconds and retry up to 2 times.
Disconnecting from Gmail Server and sleeping ...
Reconnecting to the from Gmail Server.
Get XOAuth credential from C:\Documents and Settings\xxxx/.gmvault/xxxx@xxxx.xx.oauth.

Error when reaching Gmail server. Wait 4 seconds and retry up to 2 times.
Error: UID command error: BAD ['Could not parse command'].

=== Exception traceback ===
Traceback (most recent call last):
  File "gmv\gmv_cmd.pyc", line 759, in run
  File "gmv\gmv_cmd.pyc", line 723, in _sync
  File "gmv\gmvault.pyc", line 602, in sync
  File "gmv\gmvault.pyc", line 565, in _sync_emails
  File "gmv\gmvault.pyc", line 432, in _common_sync
  File "gmv\imap_utils.pyc", line 174, in wrapper
  File "gmv\imap_utils.pyc", line 109, in reconnect
error: UID command error: BAD ['Could not parse command']

=== End of Exception traceback ===

**Comment by gaubert** [comment]
compression issue solved.

**Comment by SimonWoolf** [comment]
I have this issue. Slightly different line numbers in the stacktrace, possibly due to a newer version, but otherwise the same. I'm on the latest version (1.9.1).

```
$ gmvault sync --type custom --imap-req "Since 19-July-2018" xxx@gmail.com
Odd. Use default python2.7.x or 2.6.x distribution.

Use gmvault-db located in /home/simon/gmvault-db.

Activate Gmvault db cleaning.
Create defaults in /home/simon/.gmvault/gmvault_defaults.conf. Please touch this file only if you know what to do.
Authentication performed with Gmail OAuth2 access token.

Get OAuth2 credential from /home/simon/.gmvault/xxx@gmail.com.oauth2.


Connect to Gmail server.

Perform custom synchronisation with imap request: Since 19-July-2018.

Start synchronization (2018-11-03T11h38m45s).

Start emails synchronization.
Error when reaching Gmail server. Wait 1 second(s) and retry up to 2 times.
Disconnecting from Gmail Server and sleeping ...
Reconnecting to the from Gmail Server.
Get OAuth2 credential from /home/simon/.gmvault/xxx@gmail.com.oauth2.

Error when reaching Gmail server. Wait 2 second(s) and retry up to 2 times.
Disconnecting from Gmail Server and sleeping ...
Reconnecting to the from Gmail Server.
Get OAuth2 credential from /home/simon/.gmvault/xxx@gmail.com.oauth2.

Error when reaching Gmail server. Wait 4 second(s) and retry up to 2 times.
Error: UID command error: BAD ['Could not parse command']. 

=== Exception traceback ===
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gmv/gmv_cmd.py", line 746, in run
    self._sync(args, credential)
  File "/usr/local/lib/python2.7/dist-packages/gmv/gmv_cmd.py", line 712, in _sync
    emails_only = args['emails_only'], chats_only = args['chats_only'])
  File "/usr/local/lib/python2.7/dist-packages/gmv/gmvault.py", line 626, in sync
    self._sync_emails(imap_req, compress = compress_on_disk, restart = restart)
  File "/usr/local/lib/python2.7/dist-packages/gmv/gmvault.py", line 589, in _sync_emails
    imap_ids = self._common_sync(timer, "email", imap_req, compress, restart)
  File "/usr/local/lib/python2.7/dist-packages/gmv/gmvault.py", line 435, in _common_sync
    imap_ids = self.src.search(imap_req)
  File "/usr/local/lib/python2.7/dist-packages/gmv/imap_utils.py", line 189, in wrapper
    reconnect(args[0], nb_tries, 2, err, m_sleep_time)
  File "/usr/local/lib/python2.7/dist-packages/gmv/imap_utils.py", line 124, in reconnect
    raise rec_error
error: UID command error: BAD ['Could not parse command']

=== End of Exception traceback ===
```
