### ISSUE TITLE
Can't install gmvault via pip

### ISSUE THREAD

**Issue by voltagex** [gaubert/gmvault#170]
voltagex@nightmare:/media/files/Email$ source gmvault/bin/activate
	(gmvault)voltagex@nightmare:/media/files/Email$ pip install gmvault
	Downloading/unpacking gmvault
	  Could not find a version that satisfies the requirement gmvault (from versions: 1.0-beta, 1.5-beta, 1.6-beta, 1.7-beta, 1.8-beta, 1.8.1-beta)
	Cleaning up...
	No distributions matching the version for gmvault
	Storing debug log for failure in /home/voltagex/.pip/pip.log
	(gmvault)voltagex@nightmare:/media/files/Email$ less /home/voltagex/.pip/pip.log
	(gmvault)voltagex@nightmare:/media/files/Email$ pip install --pre gmvault
	Downloading/unpacking gmvault
	  Downloading gmvault-1.8.1-beta.tar.gz (93kB): 93kB downloaded
	  Running setup.py (path:/media/files/Email/gmvault/build/gmvault/setup.py) egg_info for package gmvault
	    PATH = /media/files/Email/gmvault/build/gmvault/./src/gmv/gmvault_utils.py

	    1.8.1-beta
	    Gmvault version = 1.8.1-beta

	Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.7 (from gmvault)
	Downloading/unpacking Logbook==0.4.1 (from gmvault)
	  Downloading Logbook-0.4.1.tar.gz (96kB): 96kB downloaded
	  Running setup.py (path:/media/files/Email/gmvault/build/Logbook/setup.py) egg_info for package Logbook

	Downloading/unpacking IMAPClient==0.9.2 (from gmvault)
	  Could not find a version that satisfies the requirement IMAPClient==0.9.2 (from gmvault) (from versions: 0.10.2, 0.10.2)
	  Some externally hosted files were ignored (use --allow-external to allow).

    Python 2.7.6 (default, Mar 25 2014, 12:34:44)
    [GCC 4.8.2] on linux2

**Comment by stephenjamieson** [comment]
```
pip install --upgrade https://github.com/gaubert/gmvault/tarball/gmv-1.8.2 --allow-external
```

I use this now

**Comment by ashleyblackmore** [comment]
Still necessary for installation. This is crazy. What the hell is up with pip?

**Comment by gaubert** [comment]
Hi All,

I am working on a new version supporting OAUTH2 to be ready before Google
switch off the OAUTH support (20th of April).
The new version will use an updated IMAPClient and I will as well update
the setup.py. So that issue will disappear and Gmvault will be again easily
installable with pip.
Just wait a bit more for the new release. I am testing and so far it is
looking good.

**Comment by gaubert** [comment]
Fixed
