### ISSUE TITLE
Unable to restore my mails

### ISSUE THREAD

**Issue by aonyango** [gaubert/gmvault#172]
Hello,

I wanted to move my all of my emails from one account to another.  I spent hours and days syncing my account and now when I go to restore, it will only upload 84 emails of a total of nearly 30k.  Please advise what the issue could be.

**Comment by gaubert** [comment]
You have to disable compression that as been dropped by GMAIL.

**Comment by Gmail2016** [comment]
Please help me. I really need to restore my emails as someone hacked my account. I have approx 25000 emails but thankfully I had used gmvault to backup my emails. however I am getting this error too (as mentioned above) and don't know what to do. Could someone please explain the steps to me and help me please.

![image](https://cloud.githubusercontent.com/assets/16752052/12383414/c615de0c-bdcb-11e5-8350-fc3c54de1165.png)
