### ISSUE TITLE
v1.8.1-beta-20130428

### ISSUE THREAD

**Issue by frankcarey** [gaubert/gmvault#173]
Error: 'ascii' codec can't encode characters in position 2346-2347: ordinal not in range(128).

**Comment by gaubert** [comment]
@frankcarey @madmack This is a unicode handling issue. I am working finally on a new version (to be released within 2-3 weeks) that will solve that problem. Let me know if you want to test it before the release.

**Comment by gaubert** [comment]
Solved new version support Oauth2. Please check new release v1.9.
