### ISSUE TITLE
i cant find my sent items

### ISSUE THREAD

**Issue by blankspot20** [gaubert/gmvault#177]
I am using Version 1.8.1 
I am running it on Windows 7

I sync my email using gmvault sync my@email.add
It downloaded around 4gig worth of emails.

Now i want to restore it using gmvault restore. It actually works but it only restores the inbox and important folders.

I also want to restore my sent folder. Is this possible?

Thanks!
RJ

**Comment by gaubert** [comment]
@blankspot20 @lainy is right . They are restored but the Sent Mail wasn't probably visible.
I will close that issue
