### ISSUE TITLE
Error: 'X-GM'MSGID'

### ISSUE THREAD

**Issue by rossoscuro** [gaubert/gmvault#179]
Hi everybody,
I am transferring the content from free gmail account to new gmail business account. The transfer worked good for 2 days (there are 67000 mails, 180gb) although sometimes the connection with imap goes down but with command "gmvault sync" it restarts, performs a check for emails already downloaded and then continues with the new emails. This morning i find this error, that gives me while checking email already transferred, and if i input the usual command for restart (gmvault sync), answer me shortly after again with the same error, each time during the control, however on the different id/mail.

this is the error:
Error: 'X-GM-MSGID'

how can fix this?

Thanks and forgive me for my bad english, i hope you can understand the issues

**Comment by wiseman** [comment]
Got the same error:

```
Process email num 39498 (imap_id:76774) from 2002-10.
Process email num 39499 (imap_id:76775) from 2002-03.

== Processed 39500 emails in 3m 33s. 269975 left to be stored (time estimate 24m 16s).==

Error: 'X-GM-MSGID'.

=== Exception traceback ===
Traceback (most recent call last):
  File "gmv/gmv_cmd.pyc", line 759, in run
  File "gmv/gmv_cmd.pyc", line 677, in _sync
  File "gmv/gmvault.pyc", line 602, in sync
  File "gmv/gmvault.pyc", line 565, in _sync_emails
  File "gmv/gmvault.pyc", line 469, in _common_sync
KeyError: 'X-GM-MSGID'

=== End of Exception traceback ===
```

**Comment by gaubert** [comment]
@wiseman  For some reason the email with imap_id 76775 hasn't got a X-GM-MSGID. 
Please go in the db directory and look for  it.
Enable the debug to get the Gmail id for that email and find it the gmvault db. Then have a look at it and send it to me if it isn't an important email. I will include it in my test suite.
Then you remove it for the moment from the gmvault-db and launch the restore again with --resume

**Comment by gaubert** [comment]
I have not fixed the problem because I do not explain it but I catch the error and ignore the email for that run and as well print some debugging information. 
So now it is not going to fail but it is going to continue processing the next email in the cleaning process and I might get some information regarding the issue next time it is encounterered if a user reports it.

@wiseman I propose to close when the next version will be released.

**Comment by gaubert** [comment]
@wiseman I did fix that issue.I will close it in the next release
