### ISSUE TITLE
Issue restoring to alternative gmail account

### ISSUE THREAD

**Issue by Champignacs** [gaubert/gmvault#181]
Hi Guillaume,

Sorry for reaching out to you, I have tried all I could think of but no luck.
I have backed up a google apps account and got 56000 emails in my db.
I tried to restore to a free gmail account and it gave me:

Cannot reach the Gmail server. Wait 1 seconds and retrying.
Disconnecting from Gmail Server and sleeping ...
Reconnecting to the from Gmail Server.

I read that I should try this in the config file: enable_imap_compression=False

I did and then it transferred for about an hour without any disconnections and was happy until I git this again:

Cannot reach the Gmail server. Wait 1 seconds and retrying.
Disconnecting from Gmail Server and sleeping ...
Reconnecting to the from Gmail Server.

I assumed Google blocked me so waited until this AM from a different location with 100mbps up and down and still no luck :(

I am running gmvault-v1.8.1-beta on OSX 10.8.5.
Would you be able to kindly assist me?

Kind regards,

Simon

**Comment by gaubert** [comment]
Hi Simon sorry for the late answer. If Google throttles you. You can then use the --resume option to restart your restore from where you were.
