### ISSUE TITLE
OAuth1 for Google accounts is going away on April 20, 2015

### ISSUE THREAD

**Issue by amannn** [gaubert/gmvault#187]
Also see: here https://support.google.com/accounts/answer/6140397

**Comment by gaubert** [comment]
Hi I am back. I am working on a new version that will first fix the followings and later on a new version will provide additional fixes and features
- allow connection with oauth2
- support of latest imapclient
- deployment with pip and for windows and mac osx

I hope to have it ready within 3 weeks.

**Comment by gaubert** [comment]
New version in test mode.

**Comment by manuelmeurer** [comment]
Will 1.8.1-beta continue working until this is resolved?
What's the ETA on 1.8.2 and 1.9?
Thanks for your work on this! :smile:

**Comment by gaubert** [comment]
I am working to release 1.9 that should be ready by end of today or
tomorrow.

**Comment by manuelmeurer** [comment]
Awesome! :+1:

**Comment by gaubert** [comment]
Solved new version support Oauth2. Please check new release v1.9.
