### ISSUE TITLE
GMVault project stauts

### ISSUE THREAD

**Issue by megrez7** [gaubert/gmvault#188]
Hi All,

I am planning to deploy some kind of gmail backup for myself and recommend and install for few friends as all of them come to me and ask for support.

However, I am little bit worried about the project status. Is it still alive? Seems like there was no new features, not updates nor even any small change release for long months. If the project is no longer alive, there is no sense to donate it what is natural in case we will start using it.

Please let me know.

Megrez

**Comment by gaubert** [comment]
Hi I am back. I am working on a new version that will first fix the followings and later on a new version will provide additional fixes and features
- allow connection with oauth2
- support of latest imapclient
- deployment with pip and for windows and mac osx

I hope to have it ready within 3 weeks.

**Comment by gaubert** [comment]
I am back. You can donate because I want it to live again
