### ISSUE TITLE
Run on Windows (Python Installation from Pypi)

### ISSUE THREAD

**Issue by SerikASA** [gaubert/gmvault#191]
Hi, guys !
I need help for running Gmvault on Windows (Python Installation from Pypi).
I have python 2.7.9 on Windows and installed gmvault-1.8.1-beta ( python setup.py install )
When I tried to start it I got error.

e:\>python gmvault
e:\Python27\python.exe: can't find '__main__' module in 'gmvault'

**Comment by SerikASA** [comment]
I can not use the windows ready version because I have extra python scripts. Perhaps there is an option to call Gmvault with the parameters from the py script. ?

**Comment by SerikASA** [comment]
I found it !

import gmv.gmv_cmd as runner
runner.bootstrap_run()

How I can add parameters ?

**Comment by gaubert** [comment]
Hi I am back. I am working on a new version that will first fix the followings and later on a new version will provide additional fixes and features
- allow connection with oauth2
- support of latest imapclient
- deployment with pip and for windows and mac osx

I hope to have it ready within 3 weeks.

**Comment by gaubert** [comment]
Hi on windows please install the package version with the installer http://bit.ly/1cdjLyv
If you want to use pip then you will have to wait because the pip install is broken due to IMAPClient

**Comment by gaubert** [comment]
@SerikASA DO you want to test the latest version ? I can send you a preview version if you let me know which version you run

**Comment by gaubert** [comment]
@SerikASA fixed in v1.9 which has been released
