### ISSUE TITLE
X-GM-MSGID error

### ISSUE THREAD

**Issue by emmawinston** [gaubert/gmvault#197]
Hi,

I'm attempting to use gmvault to back up email on OS X Yosemite, but about 8000 emails in I receive the following error: 

Process email num 8800 (imap_id:67056) from 2010-02.
Error: 'X-GM-MSGID'. 

=== Exception traceback ===
Traceback (most recent call last):
  File "gmv/gmv_cmd.pyc", line 759, in run
  File "gmv/gmv_cmd.pyc", line 677, in _sync
  File "gmv/gmvault.pyc", line 602, in sync
  File "gmv/gmvault.pyc", line 565, in _sync_emails
  File "gmv/gmvault.pyc", line 469, in _common_sync
KeyError: 'X-GM-MSGID'

=== End of Exception traceback ===

I get this regardless of whether I'm authorising by oAuth or password. I've seen [this](https://github.com/gaubert/gmvault/issues/179) but it states that the issue is fixed. Any ideas? 

Edited to add - this is the 1.8.1 beta version which is the only one available from the download page on gmvault.org. Is there another version I should be using, and if so where can I obtain it? I can't seem to get the easy_install version to download due to permissions errors so am a bit stuck.

**Comment by gaubert** [comment]
Yes I know about it. It will be fixed in 1.9 that I will release today or tomorrow.

**Comment by gaubert** [comment]
@emmawinston solved in v1.9. Please check new release
