### ISSUE TITLE
encryption broken since v1.9

### ISSUE THREAD

**Issue by gaubert** [gaubert/gmvault#202]
Encryption doesn't work anymore. To be fixed

**Comment by gaubert** [comment]
Fixed in v1.9.1

**Comment by gaubert** [comment]
close it now

**Comment by jeffbowen** [comment]
Any plans for a 1.9.1 release ever?

**Comment by jeffbowen** [comment]
Looks like 1.9.1 was released March 31, right after I asked. Ha. Nice.
