### ISSUE TITLE
gmvault error: 5d format: a number is required, not set

### ISSUE THREAD

**Issue by hsgen** [gaubert/gmvault#208]
I have no idea what to do. Was restoring my emails to a new email account and got this error message. What should I do?
Thank you

**Comment by gaubert** [comment]
@hsgen What version are you using and on which platform ?
I need to get more info to help. Please re-run the same gmvault command with the --debug option and send me via email the complete console output such that I can understand the source of the issue.

Thanks in advance

**Comment by gaubert** [comment]
@hsgen now fixed in 1.9.1 which is in testing. See #218

**Comment by gaubert** [comment]
close it now
