### ISSUE TITLE
Error while restoring emails - Exception

### ISSUE THREAD

**Issue by shivapreeta** [gaubert/gmvault#210]
Hi

Pl help me asap as i need to restore within 2 days. The exception says:
Pushing email body with id ****
Applying labels to the current batch of emails
Error: %d format:  a number is required, not set

After processing 400 emails, i am getting this error. I tried resume option, still same error. Kindly help me asap.

**Comment by gaubert** [comment]
@shivapreeta What version are you using and on which platform ?
I need to get more info to help. Please re-run gmvault with the --debug option and send me via email the complete console output such that I can understand the source of the issue.

Thanks

**Comment by gaubert** [comment]
@shivapreeta It seems to be the issue that I had when applying non-ascii labels (which is very likely if you are from India). It has been fixed in 1.9.1. I can produce a test version for you. Are you on Windows ?

**Comment by gaubert** [comment]
close it now
