### ISSUE TITLE
Chinese Chats folder localization

### ISSUE THREAD

**Issue by mhsmith** [gaubert/gmvault#213]
The folder name is "聊天".

The following worked for me:
`chat_folder=[ u'[Google Mail]/聊天', u'[Gmail]/聊天' ]`

**Comment by gaubert** [comment]
@mhsmith Thank you very much !!
I have added it in the configuration file for version 1.9.1.
Many thanks also for the donation !!

+1

**Comment by gaubert** [comment]
I will close that one for clarity
