### ISSUE TITLE
HOW TO RESTORE MAILS JUST FROM A SPECIFIC LABEL

### ISSUE THREAD

**Issue by nicosilber** [gaubert/gmvault#216]
Hello Guillaume, 

I have a google apps email nicolas@silber.es and I have a label called "nico".

I want to backup only that label so that I can restore that label in my new email account backupsilber@gmail.com.

I tried to google my answer but was not sure about what to do:

What would be the command to execute?

a) gmvault sync -t custom -g "in:nico" nicolas@silber.es

or

b) gmvault sync --type custom --gmail-req 'in:nicolas@silber.es from:nicolas@silber.es' 'backupsilber@gmail.com' -c no

Once I downloaded the label can I restore it in my new account (backupsilber@gmail.com) using the regular command??  gmvault restore backupsilber@gmail.com 

Appreciate your help!
Regards
Nicolas

**Comment by nicosilber** [comment]
Please answer me when you can

**Comment by gaubert** [comment]
@nicosilber Here is what you have to do:
```
./gmvault sync --type custom -g 'in:mylabel' myemail@gmail.com
```

Once downloaded just restore the gmvault-db where you did save the emails.

Donation always appreciated to support the project if it solves your issues.

Thanks.

**Comment by nicosilber** [comment]
thank you , I will try!

**Comment by nicosilber** [comment]
Hello @gaubert I am trying to restore a specific label in my gmail called backupfinal and it is giving me the following error.

![gmvault](https://cloud.githubusercontent.com/assets/13722719/9276252/16e0267c-4279-11e5-8715-ef0e7bf022af.jpg)

Can you help me?

**Comment by nicosilber** [comment]
After this error if I again execute

./gmvault sync --type custom -g 'in:mylabel' myemail@gmail.com

it will resume from the point it was disconnected or I should execute

./gmvault sync --type custom -g 'in:mylabel' myemail@gmail.com --resume

Please advice, thank you
Nicolas

**Comment by gaubert** [comment]
@nicosilber it seems to me that you are running multiple clients in parallel. Are you sure that the others were finished ? I did two additional tests for two different labels and it is working perfectly on Windows and Linux so I think that this is issue is coming for the way you use Gmvault

**Comment by gaubert** [comment]
@nicosilber I didn't get any answer. I will clause that issue.
