### ISSUE TITLE
ERROR WHILE RESTORING EMAILS """format: a number is required, not set""

### ISSUE THREAD

**Issue by nicosilber** [gaubert/gmvault#218]
Hello, I already backup a google apps account with success. There are 55k emails in total backup up.

Now I want to restore that 55k emails in a normal gmail account.
I am using the command gmvault restore backupsilber@gmail.com
The restore process starts OK without any problem and it continues like that for hours. But after 8 or 9 hours the restore process give me the following error: """format: a number is required, not set""
and it stops.

If I want to resume the process again y execute the command  gmvault restore backupsilber@gmail.com but the problem is that it does not resume. It starts again from zero. I am attaching you screenshots

First screenshot shows gmavault before the error: you will see it says 45.172emails to go
![gmvault error](https://cloud.githubusercontent.com/assets/13722719/9200742/b4c3e2ae-401f-11e5-8438-c86c325dd381.png)

In the second screenshot you will see the error itself.
![gmvaulterror2](https://cloud.githubusercontent.com/assets/13722719/9200805/f0f92e64-401f-11e5-9c7a-e4610819544d.png)

In the third screenshot you will see that when I resume the process it starts again from zero and not from the point it was stopped
![gmvault error3](https://cloud.githubusercontent.com/assets/13722719/9200839/327fda9a-4020-11e5-8f8e-d53e6d8cc9b9.png)
.
For your info I am using windows 10 home x64bit
Thank you very much
Nicolas

**Comment by nicosilber** [comment]
Just for your info I am already doing --debug so I can send the log to you.
Thank you
Nicolas

**Comment by gaubert** [comment]
Ok there was an issue with the labels and I fixed it (See the other related issues).
I have created a windows alpha here:
https://www.dropbox.com/s/h9fxf2p46s1213d/gmvault_installer_v1.9.1.exe?dl=0

Could you please install it and try it. It might still be broken because it requires further testing. Let me know if you can try it and it is solves your issues.

Thks

**Comment by nicosilber** [comment]
Thank you,

**Comment by gaubert** [comment]
It should not be closed until you have tested and validated that it will work.

**Comment by nicosilber** [comment]
Ok gaubert until now everything is running without the error. I will let you know if something happens.

Just for your info I am now restoring using this command: 

gmvault restore backupsilber@gmail.com --debug

My question is: is it the same restoring with --debug than without --debug

The result is the same? or should I restore using without --debug?

**Comment by nicosilber** [comment]
Hello Gaubert, 

I could not finnish the restore. It gave me a new error.
i tried two times. Both times the restore process gave me error. Please look at the screenshot
![gmvault2](https://cloud.githubusercontent.com/assets/13722719/9223906/c2e91704-40d4-11e5-9181-d2c6f9611dcb.png)

At this moment I am trying for the 3rd time. If I have the same error I will upload another screenshot and also the log.

Will keep you posted,
Thank you for your support

**Comment by nicosilber** [comment]
i have sent you the log of the error by email

**Comment by gaubert** [comment]
@nicosilber Thanks. There was an issue with the previous version I sent you. Sorry.
Here is the new version that hopefully should solve the issue: https://www.dropbox.com/s/i7gubmmx4u71eg2/u1-gmvault_installer_v1.9.1.exe?dl=0

Could you please test it and let me know if it is working ?

Many thanks for the testing

**Comment by nicosilber** [comment]
Ok Guillaume I will test it again.
Just for your info: 2 days ago you sent me an alpha version 1.9.1 to test: https://github.com/gaubert/gmvault/issues/218#issuecomment-130064510

The version you just sent me is the same one? or it's different? Just asking because both are v1.9.1
Thank you
Nicolas

**Comment by gaubert** [comment]
@nicosilber It is a different one it is called u1-gmvault but when you install it, it will install itself as v1.9.1

Thanks for the time spent testing.

**Comment by nicosilber** [comment]
Hello gaubert I wanted to let you know the problem was finally solved with your build
https://www.dropbox.com/s/i7gubmmx4u71eg2/u1-gmvault_installer_v1.9.1.exe?dl=0
Thank you very much!!!!!
Nicolas

**Comment by nicosilber** [comment]
I think you can close this issue now : )

**Comment by gaubert** [comment]
@nicosilber very good

**Comment by Boronkee** [comment]
Hi there, i'm getting the same error as nicosilber, I tried to download the file that solved that but the link lead to a 404 :/

**Comment by Gmail2016** [comment]
Hi could someone please send the file again. The file is not available for downloading.

**Comment by Sandra016** [comment]
Many users like me keep facing issues while operating Gmvault.
So I went searching for an alternative to Gmvault & found a well-written article on [Gmvault errors](http://sysc.org/gmvault-alternative/) and solutions to those errors.

This blog post helped to efficiently save my Yahoo emails locally.
