### ISSUE TITLE
Error import with trailing null

### ISSUE THREAD

**Issue by jolafrite** [gaubert/gmvault#220]
Hi

First thanks for your tool.

What is the current status for the issue #212 ?
I have few emails I can't import because of ^@
I'm using the github version of gmvault.

I'm not familiar with python but if I can help I would be happy to do so.

**Comment by jolafrite** [comment]
I did find a way to solve this issue
It's not very nice but now I can import my emails

In the file [imap_utils.py]https://github.com/gaubert/gmvault/blob/1d9915cca9c3805cbc4051e308918e844ab15e1e/src/gmv/imap_utils.py#L763 line 763 

I just add the following line to remove every null

```python
a_body = a_body.replace("\0", '')
```

Based on this conversation http://stackoverflow.com/a/12879473/1551610 null is forbidden in an email anyway.

**Comment by gaubert** [comment]
Ok I will add it tomorrow to treat all issues with null character. It will be included in 1.9.1

**Comment by jolafrite** [comment]
It's the fastest solution I found in the few hours I got but I still have plenty of questions.
1- Does imap only fails if the null is at the end or also in the body
2- This replace might also remove \\0
3- I don't know if it's possible to find the null character instead of \0

**Comment by gaubert** [comment]
@jolafrite I need to check this problem. I didn't have time yet but hope to do it this week.

**Comment by gaubert** [comment]
@jolafrite Yes I checked and we should only clean non mime type parts so it isn't so straight forward.
Would you mind if it isn't too personnal sending me the email which has caused the issue to you ?
I would like to make some test with a real email. Merci

**Comment by jolafrite** [comment]
I actually have an eml right here and it's a spam so I'm ok with the content
How can I pm you the file ?

**Comment by gaubert** [comment]
yes or send me an email.

Thanks

**Comment by gaubert** [comment]
@jolafrite Did you send me the email ?

**Comment by gaubert** [comment]
@jolafrite I didn't get your email. Do you intend to send it ? Many thanks

**Comment by gaubert** [comment]
@jolafrite I've also modified version gmv.1.9.1 to mitigate that problem. Would you like to test it? If you let me know on which platform, I can prepare a package for you. It seems that you are on windows. Is it correct ?

**Comment by gaubert** [comment]
@jolafrite I've finally changed the code to handle the null characters. In case of error I try to clean the null characters brut force in the email because I didn't want to have to parse the email for the moment. 
I have tested it with a faulty email and it worked. Could you make a test ? One more issue to fix and I will prepare 1.9.1

**Comment by gaubert** [comment]
@jolafrite Did not get any feedback from you. I did fixed it but would really like to have somebody else testing it.
