### ISSUE TITLE
No email id returned by IMAP APPEND command

### ISSUE THREAD

**Issue by jolafrite** [gaubert/gmvault#222]
Hi

I am trying to restore a lots of emails
and now I get a loop with the error "No email id returned by IMAP APPEND" command
What could be the reason of that ?

Thanks

**Comment by gaubert** [comment]
for some reasons GMAIL doesn't accept one of your emails. it is affecting more than one email ?

**Comment by jolafrite** [comment]
yes actually when I delete one, the new one gives me the same message.
I tried 5 emails and gave up

**Comment by gaubert** [comment]
@jolafrite send me the log output with --debug. I would also need to see an email to understand.

**Comment by gaubert** [comment]
@jolafrite Do you still have the problem ?

**Comment by gaubert** [comment]
@jolafrite Hello one more call out and I will close that one.

**Comment by jolafrite** [comment]
Hi, sorry very busy
In the couple of days I have to use gmvault intensively 
I have a challenge, save and restore a 20GB email box
I will tell you if I get this error

**Comment by gaubert** [comment]
@jolafrite did you do the tests ?

**Comment by wandmdave** [comment]
Hi.  Thank you so much for this program.  It is very helpful.  However I am currently having the same issue jolafrite was having and wondered if you could help?  I have forwarded an email that I cannot restore (from the account I backed up) as well as the debug log file generated when trying to restore to the new account.

Troubleshooting I have done:
I had tried restoring once using gmvault 1.8.1 for windows and it got through 700+ then stopped.  When I tried again (without the resume flag) it started with the append errors.  I then quit and tried it with the resume flag but same thing.  I tried restoring to a test gmail account I just created and it would restore (unfortunately I really need to use the email I'm trying to restore to if possible so I can't just create a new one to work around this).  Finally I uninstalled gmvault, deleted everything in my user folder and rebooted.  Then I installed the latest version of gmvault, made a new backup, and started to restore from that.  It got through around 50 and then started the append errors again.

**Comment by gaubert** [comment]
@wandmdave @jolafrite fixed in v.1.9.1
