### ISSUE TITLE
chats after Jan 2014 not sync

### ISSUE THREAD

**Issue by shellyjang** [gaubert/gmvault#223]
I did a complete sync of both email/chats and for some reason there are no chats that took place after Jan 2014 in the chats/subchats- folder. Any idea?

**Comment by gaubert** [comment]
@shellyjang chats after Jan 2014 are not available via IMAP Gmail anymore so they cannot be saved.

**Comment by shellyjang** [comment]
is there an alternative way to download the chats then?

**Comment by gaubert** [comment]
@shellyjang Not that I know. Sorry
