### ISSUE TITLE
Error: invalid literal for long() with base 10

### ISSUE THREAD

**Issue by MrKWatkins** [gaubert/gmvault#225]
Hi,

I'm using Gmvault v1.9, release date 2015-04-21. Recently I upgraded my PC to Windows 10 from Windows 8.1. Ever since then Gmvault has been failing towards the end of the backup. It copies the emails down fine but then I receive the following error:

```
Look for emails/chats that are in the Gmvault db but not in Gmail servers anymore.

Read all gmail ids from the Gmvault db. It might take a bit of time ...

Error: invalid literal for long() with base 10: '1508578268665945013-Deep-Thought'.

=== Exception traceback ===
Traceback (most recent call last):
  File "gmv\gmv_cmd.pyc", line 741, in run
  File "gmv\gmv_cmd.pyc", line 692, in _sync
  File "gmv\gmvault.pyc", line 619, in sync
  File "gmv\gmvault.pyc", line 746, in check_clean_db
  File "gmv\gmvault_db.pyc", line 329, in get_all_existing_gmail_ids
ValueError: invalid literal for long() with base 10: '1508578268665945013-Deep-Thought'

=== End of Exception traceback ===
```
Deep-Thought is the name of my PC Gmvault is running on.

**Comment by gaubert** [comment]
You have renamed one of the email file in the gmvault-db:
1508578268665945013-Deep-Thought
Deep-Thought is not a standard name. So you should remove that file from
the gmvault-db (remove 1508578268665945013-Deep-Thought.meta and
1508578268665945013-Deep-Thought.eml.gz).

**Comment by MrKWatkins** [comment]
Yeah that was it. I backup my emails into my OneDrive - that will add the name of the machine name if there was a collision with the file on the server. Must've happened somehow when OneDrive resynced after I upgraded to Windows 10.

Thanks for your help!

**Comment by gaubert** [comment]
@MrKWatkins ok very good
