### ISSUE TITLE
Gmvault failing

### ISSUE THREAD

**Issue by arjunpunnam** [gaubert/gmvault#226]
Iam unable to navigate to the access grant page and later when I hit the return key in the terminal im seeing the below message
Token upgrade failed! Could not get OAuth access token.
 Did you grant gmvault access in your browser ?
=== Exception traceback ===
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gmv/credential_utils.py", line 112, in get_oauth_tok_sec
    final_token = gdata_serv.UpgradeToOAuthAccessToken(request_token)
  File "/Library/Python/2.7/site-packages/gdata/service.py", line 564, in UpgradeToOAuthAccessToken
    'body': response.read()})
TokenUpgradeFailed: {'status': 400, 'body': 'The token is invalid.\n\n', 'reason': 'Non 200 response on upgrade'}

Do I need to change anything before granting access?Pardon me if Im sounding Naive.

<img width="1280" alt="screen shot 2015-10-03 at 3 13 45 pm" src="https://cloud.githubusercontent.com/assets/13356597/10264679/61f84614-69e1-11e5-9d12-52f1d21d143c.png">

**Comment by mattstein** [comment]
@arjunpunnam Try upgrading Gmvault, this looks like it's sending you to a deprecated authorization URL.

**Comment by gaubert** [comment]
yes. Will close it
