### ISSUE TITLE
Getting an Exception when trying to sync by recalling the stored password under ver 1.9

### ISSUE THREAD

**Issue by abetancort** [gaubert/gmvault#227]
**Environment:**  
Clean install Gmvault  v. 1.9 on a Synology x86 NAS using the standard Python package installation method from Pypi in a virtual environment isolated sandbox and using Python v. 2.7.10-14. Backing up an email from a Google Apps Free Edition (up to 100 users).

**Call:**   

```
$>./gmvault_env/bin/gmvault sync abetancort@dummy.net -d /volume1/GoogleMail -t quick -p          

Use gmvault-db located in /volume1/GoogleMail.

Activate Gmvault db cleaning.
Authentication performed with Gmail password.
```

Error: **exit**. 

**=== Exception traceback ===**

```
Traceback (most recent call last):
  File "/volume1/@appstore/gmvault_env/lib/python2.7/site-packages/gmv/gmv_cmd.py", line 738, in run
    credential = CredentialHelper.get_credential(args)
  File "/volume1/@appstore/gmvault_env/lib/python2.7/site-packages/gmv/credential_utils.py", line 199, in get_credential
    passwd = cls.read_password(args['email'])
  File "/volume1/@appstore/gmvault_env/lib/python2.7/site-packages/gmv/credential_utils.py", line 173, in read_password
    cipher       = blowfish.Blowfish(cls.get_secret_key(cls.SECRET_FILEPATH % (gmvault_utils.get_home_dir_path())))
  File "/volume1/@appstore/gmvault_env/lib/python2.7/site-packages/gmv/credential_utils.py", line 71, in get_secret_key
    with open(a_filepath).read() as f:
AttributeError: __exit__    
```

**=== End of Exception traceback ===**

**Comment by marcelofernandez** [comment]
It happens to me as well.

**Comment by marcelofernandez** [comment]
It was easy to debug and fix this one. Just delete ".read()" on this line: https://github.com/gaubert/gmvault/blob/master/src/gmv/credential_utils.py#L72

...because the .read() call on the file is redundant (it is made below, anyways).

It works fine like this:
```
 70         if os.path.exists(a_filepath):                                           
 71             with open(a_filepath) as f:                                          
 72                 secret = f.read() 
```

**Comment by abetancort** [comment]
Gracias / Thanks Marcelo.

Saludos,


Alfonso C. Betancort
móvil       +34 636 04 46 03
skype      alfonso.betancort
hangouts alfonso@betancort.net 
Sent from my iPad Air using Google for Work...

El 15 oct 2015, a las 11:58 PM, Marcelo Fernández <notifications@github.com> escribió:

It was easy to debug and fix this one. Just delete ".read()" on this line: https://github.com/gaubert/gmvault/blob/master/src/gmv/credential_utils.py#L72

...because the .read() call on the file is redundant (it is made below, anyways).

It works fine like this:

 70         if os.path.exists(a_filepath):                                           
 71             with open(a_filepath) as f:                                          
 72                 secret = f.read()

**Comment by CumpsD** [comment]
Having the same problem here.

How do I apply this fix without waiting for a new release? I used ```pip install```

**Comment by CumpsD** [comment]
Nevermind, edited it in lib and it worked with this fix, thanks :+1:

**Comment by maurizio-emmex** [comment]
Thanks Marcelo,
your fix works in FreeBSD too.

**Comment by gaubert** [comment]
Check the new version v1.9.1 as the problem should have been fixed. Let me know
