### ISSUE TITLE
GMV keeps stopping after 250 emails no error nothing just stops

### ISSUE THREAD

**Issue by thorrrr** [gaubert/gmvault#230]
GMV keeps stopping after a few thousand emails no error nothing just stops.

It logs in fine i just type

gmvault sync myemailaddress@gmail.com (i do type my actual email:)

I have tried it 4 times today but will not go any further????

I am on WHS 2011 as administrator  with lates version of GMV

http://pastebin.com/N48LxKWN

**Comment by gaubert** [comment]
Check the new version v1.9.1 as the problem should have been fixed. Let me know
