### ISSUE TITLE
RFE: Follow XDG Base Directory Specification

### ISSUE THREAD

**Issue by zabbal** [gaubert/gmvault#231]
Would be nice if gmvault would follow specification for default configuration directory http://standards.freedesktop.org/basedir-spec/latest/

So the config should be in $XDG_CONFIG_HOME/gmvault instead of ~/.gmvault

**Comment by gaubert** [comment]
Well this is for a particular case here at the moment as it isn't well spread on all Unixes.
Beside, you can also change the location of the .gmvault dir by setting the GMVAULT_DIR env variable.
Will close that one
