### ISSUE TITLE
Error number 13 issue

### ISSUE THREAD

**Issue by rflesner** [gaubert/gmvault#235]
Hi,
I just downloaded and ran gmvault on my gmail account, and it got through about 80 to 85% of my mail and stopped. I then tried to do a resume, and it crashed with an "errno 13" error. I can't get it to go any further. I'm running this on a Windows 10 machine and the latest version of gmvault (1.9). Any help you can give me would be greatly appreciated. Below is the log from gmvault when I ran the resume command:

gmvault-shell>gmvault sync foo.bar@gmail.com --resume

Use gmvault-db located in C:\Users\foo/gmvault-db.

Activate Gmvault db cleaning.
Authentication performed with Gmail OAuth2 access token.

Get OAuth2 credential from C:\Users\foo/.gmvault/foo.bar@gmail.com.oauth2.

Connect to Gmail server.

Start synchronization (2015-12-11T08h02m38s).

Start emails synchronization.
Restart mode activated for emails. Need to find information in Gmail, be patient ...
Restart from gmail id xxxxxxxxxxxx (imap id 142484).
14390 emails to be fetched.
Process email num 0 (imap_id:143392) from 2015-02.
Process email num 1 (imap_id:143393) from 2015-02.
Process email num 2 (imap_id:143394) from 2015-02.
Process email num 3 (imap_id:143395) from 2015-02.
Process email num 4 (imap_id:143398) from 2015-02.
Process email num 5 (imap_id:143399) from 2015-02.
Process email num 6 (imap_id:143400) from 2015-02.
Process email num 7 (imap_id:143401) from 2015-02.
Process email num 8 (imap_id:143402) from 2015-02.
Process email num 9 (imap_id:143403) from 2015-02.
Error: [Errno 13] Permission denied: 'C:\Users\foo/gmvault-db/.info/foo.bar@gmail.com_email_last_id.sync'.

=== Exception traceback ===
Traceback (most recent call last):
  File "gmv\gmv_cmd.pyc", line 741, in run
  File "gmv\gmv_cmd.pyc", line 661, in _sync
  File "gmv\gmvault.pyc", line 607, in sync
  File "gmv\gmvault.pyc", line 570, in _sync_emails
  File "gmv\gmvault.pyc", line 545, in _common_sync
  File "gmv\gmvault.pyc", line 809, in save_lastid
IOError: [Errno 13] Permission denied: 'C:\Users\foo/gmvault-db/.info/foo.bar@gmail.com_email_last_id.sync'

=== End of Exception traceback ===

**Comment by gaubert** [comment]
Check the new version v1.9.1 as the problem should have been fixed. Let me know
