### ISSUE TITLE
unnecessary conversion to utf-8 when syncing?

### ISSUE THREAD

**Issue by agoode** [gaubert/gmvault#236]
I am testing a roundtrip operation, when I sync, then restore to another account, then sync again. I discovered this isn't always lossless. Sometimes, when the character set is not detected properly, bury_email will corrupt the output:
https://github.com/gaubert/gmvault/blob/master/src/gmv/gmvault_db.py#L447

I don't see the need for this. When I remove all the recoding, I am able to roundtrip successfully.

Why are the bodies not treated completely opaquely?

**Comment by gaubert** [comment]
@agoode I had to force a UTF-8 conversion because often Gmail wasn't reaccepting the original email. If you have better suggestion then let me know.

**Comment by mikelward** [comment]
gaubert, what encoding was the original email?  What error did you get?  It's had to know how to solve the problem without knowing what the problem is.
