### ISSUE TITLE
Unable to restore emails from gmvault

### ISSUE THREAD

**Issue by Gmail2016** [gaubert/gmvault#237]
Please help me. I really need to restore my emails as someone hacked my account. I have approx 25000 emails but thankfully I had used gmvault to backup my emails. however I am getting this error again and again and don't know what to do. Could someone please explain the steps to me and help me please. I hope I have not lost my emails.

![image](https://cloud.githubusercontent.com/assets/16752052/12383667/cc6e6a32-bdce-11e5-8243-030899af7b68.png)

**Comment by gaubert** [comment]
Check the new version v1.9.1 as the problem should have been fixed. Let me know
