### ISSUE TITLE
RESTORE STOPS WITH ERROR

### ISSUE THREAD

**Issue by formaldehyde1950** [gaubert/gmvault#239]
Windows 8.1
sync is ok
restore stops when apply labels to a section of emails
Typeerror: xd format: a number is required not set

Tried to re sync, and then restore again, but same error?

**Comment by formaldehyde1950** [comment]
Sorry, this issue is with gmvault?

**Comment by gaubert** [comment]
Check the new version v1.9.1 as the problem should have been fixed. Let me know
