### ISSUE TITLE
OAuth URL malformed

### ISSUE THREAD

**Issue by paour** [gaubert/gmvault#240]
I want to restore a friend's backup to their account, and on the first attempt, Gmvault (1.9 / github's `master`) first tries running the auth in the local browser, but since my friend is distant, I quit the browser to use the URL that gmvault then generates.

However, Google complains the request is invalid: 

```
Error: invalid_request

Required parameter is missing: response_type
```

(more parameters are missing for a proper OAuth request…

**Comment by gaubert** [comment]
fixed on 1.9.1. Just released.
