### ISSUE TITLE
it takes too much time 

### ISSUE THREAD

**Issue by ysfomo** [gaubert/gmvault#252]
this is my first time using gmvault 

I am using gm gmvault to backup my email 

I have around 30000 email and 83 GIG of emails on my gmail account 

the syncing of my email is going on for the past 5-6 days and only 8000 email has been stores around 8 GIGS 

I use to stop the syncing once in a while cause it look like gmvualt is not giving me the progress of the backup 

my issue is 

when I restart the back up it gives me like 500 email stored in the last 5 second 

and then 

I wait for like an hour and half 

to give me another massage that 

another 500 email has been stored in the psat 1 hour and 30 minutes

is the speed of the backup normal 

or something is off

thanks

**Comment by ysfomo** [comment]
sorry last massage 50 emails in the last 30 minutes

**Comment by gaubert** [comment]
@ysfomo you should do a full sync once and then only quick sync. Check the documentation and let me know if you need more help.
