### ISSUE TITLE
Error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>.

### ISSUE THREAD

**Issue by ovizii** [gaubert/gmvault#263]
As reported in the Google Group I'm adding this as an issue. https://groups.google.com/forum/#!topic/gmvault-users/ATJYg4sZNOc 

Running gmvault 1.9.1 on freeNAS which is based on freeBSD. ran perfectly for more than year. 

```
oot@gmvaulty:~/.gmvault # /usr/local/bin/gmvault sync ovidiu@domain.tld -d /mnt/gmvaulty/ --no-compression -t quick

Use gmvault-db located in /mnt/gmvaulty/.

Activate Gmvault db cleaning.
Authentication performed with Gmail OAuth2 access token.

Initiate interactive session to get OAuth2 token from Gmail.

gmvault will now open a web browser page in order for you to grant gmvault access to your Gmail.
Please make sure you're logged into the correct Gmail account (ovidiu@domain.tld) before granting access.
Press ENTER to open the browser.
You should now see the web page on your browser now.
If you don't, you can manually open:

https://accounts.google.com/o/oauth2/auth?client_id=1070918343777-0eecradokxyzi77qfo8e3stbi0mkrtog.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=https%3A%2F%2Fmail.google.com%2F

Once you've granted gmvault access, enter the verification code and press enter:
4/z_48vGZmYNWTKKxyzzRxJMeyeiQiSdvtsoL4FeJSIQo
Error: Problems when trying to connect to Google oauth2 endpoint: https://accounts.google.com/o/oauth2/token.
Error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>.

=== Exception traceback ===
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gmvault-1.9.1-py2.7.egg/gmv/gmv_cmd.py", line 743, in run
    credential = CredentialHelper.get_credential(args)
  File "/usr/local/lib/python2.7/site-packages/gmvault-1.9.1-py2.7.egg/gmv/credential_utils.py", line 235, in get_credential
    credential = cls.get_oauth2_credential(args['email'], renew)
  File "/usr/local/lib/python2.7/site-packages/gmvault-1.9.1-py2.7.egg/gmv/credential_utils.py", line 387, in get_oauth2_credential
    access_token, refresh_token, validity, type = cls._get_oauth2_tokens(email, use_webbrowser = True)
  File "/usr/local/lib/python2.7/site-packages/gmvault-1.9.1-py2.7.egg/gmv/credential_utils.py", line 342, in _get_oauth2_tokens
    response = cls._get_authorization_tokens(verification_code)
  File "/usr/local/lib/python2.7/site-packages/gmvault-1.9.1-py2.7.egg/gmv/credential_utils.py", line 306, in _get_authorization_tokens
    raise err
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>

=== End of Exception traceback ===
```

**Comment by samuelbosch** [comment]
I'd like to add that I'm getting the same error on Windows 7 (new user).

**Comment by hamhock** [comment]
gmvault-1.9.1-3 on arch-linux-64 (4.8.11-1-ARCH)

I was also getting these same errors, but ran this command and it solved it:
`gmvault sync --type quick me@gmail.com --renew-oauth2-tok`

**Comment by bricep** [comment]
I am getting this error in Windows 10... first time attempting to sync. I tried the above renew token command as well. It seems this is between Google and the app.

**Comment by gaubert** [comment]
@ovizii what version of python is installed on your NAS ? I guess python 2.7.9 or above ?
Please advise.

**Comment by ovizii** [comment]
I had/have Python 2.7.12 - had because I created a new jail, setup gmvault from scratch and am back to a working installation but the old jail will have had the exact same version.

from my side this issue can be closed.

**Comment by gaubert** [comment]
@ovizii Ok in any case in the branch gmv-1.9.2 I added an option to disable SSL cert verification when somebody is using 2.7.9 and 2.7.10. It will be in the next release

**Comment by gaubert** [comment]
Will mark it as fixed in gmv-1.9.2

**Comment by lawsonmcw** [comment]
I've been waiting to see if there was a fix for this issue.  I'm running Python 3.5.1 and see the same thing.    Looks to me like something changed on Google's end.  When I attempt to sync I see:

gmvault-shell>gmvault sync xxxxxxx@gmail.com

Use gmvault-db located in C:\Users\Lawson/gmvault-db.

Activate Gmvault db cleaning.
Create defaults in C:\Users\Lawson/.gmvault/gmvault_defaults.conf. Please touch this file only if you know what to do.
Authentication performed with Gmail OAuth2 access token.

Get OAuth2 credential from C:\Users\Lawson/.gmvault/xxxxxx@gmail.com.oauth2.

Error: Problems when trying to connect to Google oauth2 endpoint: https://accounts.google.com/o/oauth2/token.

Error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>.

=== Exception traceback ===
Traceback (most recent call last):
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmv_cmd", line 743, in run
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.credential_utils", line 235, in get_credential
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.credential_utils", line 411, in get_oauth2_credential
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.credential_utils", line 267, in _get_oauth2_acc_tok_from_ref_tok
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>

=== End of Exception traceback ===

If I attempt to resync I see:

gmvault-shell>gmvault sync --renew-oauth2-tok xxxxxx@gmail.com

Use gmvault-db located in C:\Users\Lawson/gmvault-db.

Activate Gmvault db cleaning.
Create defaults in C:\Users\Lawson/.gmvault/gmvault_defaults.conf. Please touch this file only if you know what to do.
Authentication performed with Gmail OAuth2 access token.

Get OAuth2 credential from C:\Users\Lawson/.gmvault/xxxxxx@gmail.com.oauth2.

Renew OAuth2 token (normal). Initiate interactive session to get it from Gmail.

gmvault will now open a web browser page in order for you to grant gmvault access to your Gmail.
Please make sure you're logged into the correct Gmail account (xxxxxx@gmail.com) before granting access.
Press ENTER to open the browser.
You should now see the web page on your browser now.
If you don't, you can manually open:

https://accounts.google.com/o/oauth2/auth?client_id=1070918343777-0eecradokiu8i77qfo8e3stbi0mkrtog.apps.googleusercontent.com&redirect_uri=u
rn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=https%3A%2F%2Fmail.google.com%2F

Once you've granted gmvault access, enter the verification code and press enter:
4/VCoueXw-o4nrI5XtWxjZUaL-Nk4guPBPDRnhha8IfDE
Error: Problems when trying to connect to Google oauth2 endpoint: https://accounts.google.com/o/oauth2/token.
Error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>.

=== Exception traceback ===
Traceback (most recent call last):
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmv_cmd", line 743, in run
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.credential_utils", line 235, in get_credential
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.credential_utils", line 387, in get_oauth2_credential
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.credential_utils", line 342, in _get_oauth2_tokens
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.credential_utils", line 306, in _get_authorization_tokens
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>

=== End of Exception traceback ===

**Comment by gaubert** [comment]
@lawsonmcw yep this is the same problem. I have added a fix in the branch gmv-1.9.2. Can you pull it and test it ? By default the error should still be there and you have the set the variable "disable_cert_verification" to True in the [GoogleOAuth2] group in the configuration file called gmvault_defaults.conf located by default in $HOME/.gmvault

[GoogleOauth2]
scope=https://mail.google.com/
... etc ...
disable_cert_verification=**True**`

you are running Gmvault on python 3 ? Any issues, any changes. It would be good to have gmvault supporting python 3 "officially"

Lret me know how you testings are going

**Comment by RobBlakemore** [comment]
Hi, I have same issue. Please can you confirm when v1.9.2 will be released formally?

Alternatively, please can you confirm how I get v1.9.2 on Windows - to try out the fix?  Thanks.

**Comment by vermorel** [comment]
Same problem than @RobBlakemore Willing to get v1.9.2 on Windows. @gaubert Thank you very much for your follow-up.
