### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by eriknstr** [gaubert/gmvault#266]
Hello, I just wanted to point out that the commit that added the license had the commit message "add GPLV3 licensing", and each source file has the same statement at the top which corresponds with this the commit message:

>This program is free software: you can redistribute it and/or modify
>it under the terms of the GNU General Public License as published by
>the Free Software Foundation, either version 3 of the License, or
>(at your option) any later version.

However, the license file attached at the root of the repository is not the GPLv3 license but the Affero GPLv3, which is a different license. The FSF says at https://www.gnu.org/licenses/licenses.html#AGPL:

>The GNU Affero General Public License is based on the GNU GPL, but has an additional term to allow users who interact with the licensed software over a network to receive the source for that program.

Please either update the statements of the top of each source file with the notice for AGPLv3, if your intention was to use the AGPLv3, or replace the AGPLv3 license file in the root of the repository with the GPLv3 if your intention was to use the GPLv3.

**Comment by gaubert** [comment]
@eriknstr Thanks the test files had not been updated but all the rest was since 2013. The license is AGPLv3.
