### ISSUE TITLE
How does this work with 2FA?

### ISSUE THREAD

**Issue by nk8** [gaubert/gmvault#268]
I am looking to use this, but my Gmail account has 2FA. Can we add documentation for this, or let us know that it's not yet supported? Thanks!

**Comment by chevillet** [comment]
It works perfectly with 2FA, I've been using it for a while.
I'm not 100% sure about this but, if I remember correctly, the configuration process for 2FA was the same.
When you copy/paste the URL given by Gmvault while initializing, the 2FA stuff is handled in the browser while granting Gmvault.
After, you don't need to worry about it as long as you don't revoke Gmvault access to your account.

**Comment by nk8** [comment]
Great, thanks @chevillet :)
