### ISSUE TITLE
Why is src/sync.readme encrypted?

### ISSUE THREAD

**Issue by Keith-S-Thompson** [gaubert/gmvault#269]
`file src/sync.readme` reports "Vim encrypted file data".

Apparently the encryption was applied in revision `524259a6`, 2012-07-03, "protect sync.readme".

I don't see anything that indicates what the encryption key might be.

Why is it encrypted? And if there's a good reason to encrypt it (while earlier versions are readable), why include it in a public repo?

If nothing else, I suggest including an explanation in the top-level `README.md`.

**Comment by gaubert** [comment]
This was my note file. I will remove it
