### ISSUE TITLE
Possibly valid e-mail addresses in README.md

### ISSUE THREAD

**Issue by Keith-S-Thompson** [gaubert/gmvault#270]
The top-level `README.md` file uses `foo.bar@gmail.com` in its examples.

It's very likely that somebody has that e-mail address. By publishing it, even as an example, you could expose the owner to a higher level of spam.

The usual convention is to use `...@example.com`, but that won't work here since it's gmail-specific.

I suggest registering a gmail address and using it in the examples.

**Comment by xZeroMCPE** [comment]
True, but....

**Comment by sidick** [comment]
Example.com could be used if you pretend it's a google apps account ;)

**Comment by gaubert** [comment]
If you own the foo.bar@gmail.com address you are clearly already receiving some spam. So I will leave it as it is.
