### ISSUE TITLE
Problems when trying to connect to Google oauth2 endpoint

### ISSUE THREAD

**Issue by gonzofy** [gaubert/gmvault#276]
Thanks for writing gmvault! I've been using it successfully for a long time.

I'm getting 400 errors from Google now.

I'm using v1.9.1. I have been using it successfully since it was launched and have changed nothing about the installation, so I assume Google changed something. For example, Google might have changed the API for its oauth endpoint. Yesterday and today I've had issues with gmvault authenticating with Google.

Here's what I see:

```Activate Gmvault db cleaning.
Authentication performed with Gmail OAuth2 access token.

Get OAuth2 credential from ...

Error: Problems when trying to connect to Google oauth2 endpoint: https://accounts.google.com/o/oauth2/token.

Error: HTTP Error 400: Bad Request.

=== Exception traceback ===
Traceback (most recent call last):
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.gmv_cmd", line 743, in run
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.credential_utils", line 235, in get_credential
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.credential_utils", line 411, in get_oauth2_credential
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.credential_utils", line 267, in _get_oauth2_acc_tok_from_ref_tok
HTTPError: HTTP Error 400: Bad Request

=== End of Exception traceback ===```

One minor thing: as you see above, the message in the Exception traceback appears to be a hard-coded path to `/Users/gaubert/Dev/projects/gmvault-1.8.2/` which is (a) not my laptop! and (b) not even the right version (1.8.2 exists nowhere on my computer).

**Comment by gaubert** [comment]
@gonzofy I had the same issue on an old account for testing and I had to renew the oauth2 token and now it works.
Please try to do the same and let me know

**Comment by DavidBerdik** [comment]
> @gonzofy I had the same issue on an old account for testing and I had to renew the oauth2 token and now it works.
> Please try to do the same and let me know

Did you have to renew it multiple times? It seems that I need  to renew it about once a week which is exceptionally annoying since I am trying to use gmvault to take automated backups.

**Comment by bleistift2** [comment]
> > @gonzofy I had the same issue on an old account for testing and I had to renew the oauth2 token and now it works.
> > Please try to do the same and let me know
> 
> Did you have to renew it multiple times? It seems that I need to renew it about once a week which is exceptionally annoying since I am trying to use gmvault to take automated backups.

I have to renew it about every week as well, makes the whole backup strategy unreliable.
Is the Password option still possible and why is it not recommended?

**Comment by DavidBerdik** [comment]
@bleistift2 To fix the weekly expiration, follow the instructions in these two posts:

- https://github.com/gaubert/gmvault/issues/335#issuecomment-475437988
- https://github.com/gaubert/gmvault/issues/335#issuecomment-870883693

**Comment by bleistift2** [comment]
> @bleistift2 To fix the weekly expiration, follow the instructions in these two posts:
> 
> * [Google will revoke Gmvault access March 31, 2019 #335 (comment)](https://github.com/gaubert/gmvault/issues/335#issuecomment-475437988)
> * [Google will revoke Gmvault access March 31, 2019 #335 (comment)](https://github.com/gaubert/gmvault/issues/335#issuecomment-870883693)

Thank you for your answer, I have already created the project.
Unfortunately I don't understand your recommended procedure:
"if you submit the app for verification but don't fill out the necessary forms to actually be formally verified, your project gets put in a state in which it is only available to users that are specified as test users, but since you are also not in test mode anymore, the 7-day expiration no longer happens."

How do I submit the app to verification?
Someone else called it "publish the app", I can't find either in my Google cloud platform control center.

**Comment by DavidBerdik** [comment]
> How do I submit the app to verification?
> Someone else called it "publish the app", I can't find either in my Google cloud platform control center.

Check the "Publishing status" section of https://console.developers.google.com/apis/credentials/consent.

This is how mine looks. Yours should look like this too if you have it set up properly:
![image](https://user-images.githubusercontent.com/7663225/160209771-d9c5bd53-8a0a-4fcc-96a4-7e946479d492.png)

If it doesn't look like this, you will want to click the button under the "publishing status" section. I forget what exactly the button says if you haven't pressed it. I believe it says "publish" or "release" or something like that.
