### ISSUE TITLE
S3 sync

### ISSUE THREAD

**Issue by fregante** [gaubert/gmvault#277]
As a follow-up to #56:

`s3fs-fuse` didn't work for me and Transmit.app's "Mount (S3) as disk" feature was insanely slow (10 email/minute on S3 vs 160 email/minute on disk). This might have to do with the overhead of doing every operation through S3 as opposed to just uploading.

I wish that gmvault would handle this autonomously (or by plugging into [`aws-cli`](https://github.com/aws/aws-cli))

A CloudFormation that takes care of itself (automated daily backup on Lambda or something) would be perfect for this, but that's just me dreaming ✨

**Comment by bfred-it** [comment]
Those are some beautiful tags you added and I didn't realize until now 😍
