### ISSUE TITLE
New Windows 7 Install with 2nd Factor Authentication Causes Lookup Failed

### ISSUE THREAD

**Issue by kendoori** [gaubert/gmvault#278]
Attempting new install. User has gmail with 2nd factor authentication. 

After installing software, against the account and issuing: gmvault sync foo.bar@gmail.com the system sends me to the web to authenticate, I get a paste the code, but the screen echoes back Error: Lookup Failed

You can see the transaction below.. the user is normally US-based, but is in Europe right now...

![selection_663](https://cloud.githubusercontent.com/assets/2447420/21031747/1fff5f22-bd73-11e6-9a9a-5c0fa13ef728.png)

**Comment by gaubert** [comment]
ok need to check

**Comment by gaubert** [comment]
@kendoori Was it the first time you tried to login on Gmail from that machine ? I guess so. You need to login first with a browser and then do your two step authentication from the browser.
After that you should be able to use Gmvault. I cannot overcome that problem. I can add more documentation.

**Comment by kendoori** [comment]
I was able to trigger the backups from a different machine, so am good. Why don't you close this.

**Comment by gaubert** [comment]
ok very good

**Comment by flop25** [comment]
I'm on the 1.9.2 beta from https://github.com/gaubert/gmvault/issues/285#issuecomment-277521706 and got that too. It's not the first login on that machine
