### ISSUE TITLE
Unable to restore G Suite emails to another email address.

### ISSUE THREAD

**Issue by esters** [gaubert/gmvault#300]
Good day,

Gmvault 1.9.1 on Debian 8.7 is unable to restore G Suite emails to a specified address. Below is the output of the command:

```
$ gmvault restore -a "label" -d /home/user/.backup/email/emaildb email.address@domain.com
Odd. Use default python2.7.x or 2.6.x distribution.

Use gmvault-db located in /home/user/.backup/email/emaildb.

Authentication performed with Gmail OAuth2 access token.

Get OAuth2 credential from /home/user/.gmvault/email.address@domain.com.oauth2.

Connect to Gmail server.

Start restoration (2017-04-19T12h17m09s).

Start emails restoration.

Restore emails in gmail account email.address@domain.com.oauth2.
Read email info from /home/user/.backup/email/emaildb.
Total number of elements to restore 15197.
Got all emails id left to restore. Still 15197 emails to do.

Processing next batch of 80 emails.

Pushing email body with id 1451421211634400661.
Error: 'module' object has no attribute 'six'.

=== Exception traceback ===
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gmv/gmv_cmd.py", line 750, in run
    self._restore(args, credential)
  File "/usr/local/lib/python2.7/dist-packages/gmv/gmv_cmd.py", line 625, in _restore
    emails_only = args['emails_only'], chats_only = args['chats_only'])
  File "/usr/local/lib/python2.7/dist-packages/gmv/gmvault.py", line 901, in restore
    self.restore_emails(pivot_dir, extra_labels, restart)
  File "/usr/local/lib/python2.7/dist-packages/gmv/gmvault.py", line 1145, in restore_emails
    handle_restore_imap_error(err, gm_id, db_gmail_ids_info, self)
  File "/usr/local/lib/python2.7/dist-packages/gmv/gmvault.py", line 84, in handle_restore_imap_error
    raise the_exception
AttributeError: 'module' object has no attribute 'six'

=== End of Exception traceback ===
```

List of installed packages:
```
> pip freeze
appdirs==1.4.3
asn1crypto==0.22.0
backports.ssl==0.0.9
cffi==1.10.0
chardet==2.3.0
cryptography==1.8.1
dnspython==1.15.0
enum34==1.1.6
funcsigs==1.0.2
gmvault==1.9.1
idna==2.5
IMAPClient==1.0.2
iotop==0.6
ipaddress==1.0.18
Logbook==1.0.0
Magic-file-extensions==0.2
mock==2.0.0
packaging==16.8
pbr==2.1.0
pyasn1==0.2.3
pycparser==2.17
pycrypto==2.6.1
pyOpenSSL==16.2.0
pyparsing==2.2.0
python-apt==0.9.3.12
six==1.10.0
vboxapi==1.0
virtualenv==15.1.0
```

**Comment by bobpaul** [comment]
I just encountered this bug, too. I'll probably clone and make a pull request with this fix, but in the mean time, the issue is in **mod_imap.py**

`def to_unicode(s):
    if isinstance(s, imapclient.six.binary_type):
        return s.decode('ascii')
    return s

def to_bytes(s):
    if isinstance(s, imapclient.six.text_type):
        return s.encode('ascii')
    return s
`

change to 

`def to_unicode(s):
    if isinstance(s, imapclient.imapclient.binary_type):
        return s.decode('ascii')
    return s

def to_bytes(s):
    if isinstance(s, imapclient.imapclient.text_type):
        return s.encode('ascii')
    return s
`

Probably a better fix would be to import six and use six.text_type and six.binary directly, rather than accessing them through imapclient. Then it won't break if imapclient renames its instance again.

After doing this I was able to restore a bunch of e-mails and then it crashed with something about NoneType not being iterable. I'm hoping that if I keep running it when it crashes that it'll restore more e-mails each time.

**Comment by pinsleepe** [comment]
@bobpaul fix worked for me, no errors. 

`>pip freeze
asn1crypto==0.23.0
backports.ssl==0.0.9
certifi==2017.11.5
cffi==1.11.2
chardet==3.0.4
conda==4.3.31
cryptography==2.1.4
idna==2.6
pcloud==0.0.2
pycosat==0.6.3
pycparser==2.18
pyOpenSSL==17.5.0
PySocks==1.6.7
requests==2.18.4
ruamel-yaml==0.11.14
six==1.11.0
urllib3==1.22
`

**Comment by esters** [comment]
@bobpaul fix also worked for me, I will close this issue and mark it as resolved.
