### ISSUE TITLE
oauth2 broken?

### ISSUE THREAD

**Issue by limes007** [gaubert/gmvault#348]
Since 2020-07-15 I get

>Error: Problems when trying to connect to Google oauth2 endpoint: https://accounts.google.com/o/oauth2/token.
>Error: HTTP Error 400: Bad Request. 

I'm the only one or is this a general problem?
Any solutions?

**Comment by iamvishnurajan** [comment]
I am seeing this now, in same timeframe. My last successful sync was on July 14, 2020

**Comment by iamvishnurajan** [comment]
I have no idea why it was needed, but after renewing my token with the below, it is now working.

gmvault check --renew-oauth2-tok _your_email_address@gmail.com_

**Comment by limes007** [comment]
Thanks a lot, this has helped. I temporarily switched to password storing as described here (https://github.com/gaubert/gmvault/issues/332#issuecomment-473728750), but oauth2 is much better.
