### ISSUE TITLE
"No module named response_parser" while building on Arch Linux

### ISSUE THREAD

**Issue by Edke** [gaubert/gmvault#36]
Hello.

I'm trying to create PKGBUILD for Arch Linux. I'm not very experienced in python, therefore maybe I'm missing something.

My PKGBUILD is plain simple. But building using "pip install gmvault" gives me following error:

    Downloading/unpacking gmvault
      Downloading gmvault-1.5-beta.tar.gz (51Kb): 51Kb downloaded
      Running setup.py egg_info for package gmvault
        PATH = /home/kraken/abs/gmvault-beta/src/gmvault-1.5-beta/build/gmvault/./src/gmv/gmv_cmd.py
        
        1.5-beta
        Gmvault version = 1.5-beta
        
        
    Downloading/unpacking Logbook==0.3 (from gmvault)
      Downloading Logbook-0.3.tar.gz (89Kb): 89Kb downloaded
      Running setup.py egg_info for package Logbook
        
    Downloading/unpacking IMAPClient==0.8.1 (from gmvault)
      Downloading IMAPClient-0.8.1.zip (107Kb): 107Kb downloaded
      Running setup.py egg_info for package IMAPClient
        Traceback (most recent call last):
          File "<string>", line 14, in <module>
          File "/home/kraken/abs/gmvault-beta/src/gmvault-1.5-beta/build/IMAPClient/setup.py", line 14, in <module>
            import imapclient
          File "imapclient/__init__.py", line 22, in <module>
            from response_parser import *
        ImportError: No module named response_parser
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):

      File "<string>", line 14, in <module>

      File "/home/kraken/abs/gmvault-beta/src/gmvault-1.5-beta/build/IMAPClient/setup.py", line 14, in <module>

        import imapclient

      File "imapclient/__init__.py", line 22, in <module>

        from response_parser import *

    ImportError: No module named response_parser

    ----------------------------------------
    Command python setup.py egg_info failed with error code 1 in /home/kraken/abs/gmvault-beta/src/gmvault-1.5-beta/build/IMAPClient
    Storing complete log in /home/kraken/.pip/pip.log

**Comment by gaubert** [comment]
@WebSpider Nop I will close it
