### ISSUE TITLE
add some documentation regarding backup of attachments

### ISSUE THREAD

**Issue by gaubert** [gaubert/gmvault#73]
Users asked about attachments. Put somewhere in the doc that they are saved.

**Comment by emichael** [comment]
I don't see any mention of attachments in the docs. In fact, this issue was the only thing I could find about them.

**Comment by Rustymage** [comment]
Does gmvault even backup attachments, I'm not getting this occur in my backups?

**Comment by unformatt** [comment]
Hi @gaubert, I see you closed this but do not see any documentation about attachments. Is there any?
