### ISSUE TITLE
[Gmvault] Instructions for Russian users

### ISSUE THREAD

**Issue by online** [gaubert/gmvault#77]
Hello.

Wrote a guide for Russian users in [my blog](http://mydb.ws/2012/08/17/gmvault-bekap-pochty-gmail-i-perenos-dannyx-v-drugoj-akkaunt.html). Please add a link to the instructions in [README.md](https://github.com/gaubert/gmvault/blob/master/README.md). Thanks.

**Comment by online** [comment]
@gaubert Sorry, that article is not available at the old address. Soon I will write a new one.

**Comment by gaubert** [comment]
Please and I will link it again. Many thanks Guillaume
